version: "3.8"
services:
  postgresql:
    image: postgres
    container_name: banking_core_db
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ECHO: ${POSTGRES_ECHO}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./migrations/20250602195421_create_banking_base_entities.up.sql:/docker-entrypoint-initdb.d/init.sql

  banking_core:
    build: .
    container_name: banking_core
    ports:
      - 8080:8080
